name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test:
    name: ${{ matrix.os }} - GCC
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install gcc

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install make mingw-w64 -y
          echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH
          echo "C:\ProgramData\chocolatey\lib\mingw-w64\tools\mingw64\bin" >> $GITHUB_PATH

      - name: Build & run tests
        run: make run

      - name: Clean
        run: make clean
